travis:
  secure:
    BINSTAR_TOKEN: VLquGFYMp2DkdNAb33Bg+MmfW5uI3WNRmoaefB5NCOsqZRin8cps/s6ebMq7MtMC6qmB8ylL8t2xhV38ruKI9Y/WzPpebLEUttCY+H5ZwkNmsy7h2OiBsOowQvznFRPE7xn6P+VcZhQfAKAj4xsD0Gve95f2GgOl3FgM0GH8stGuUUAVSuYPY03M/bj8lzjOlKRT0ZR1W75/CmWvLkau8qNKJ7WYCxZS3L00x15FMmNGafHyV0+JW1a8Rt7Z4A2odbLqSczlXsnrU+jOfsyDkry++g6TaVnxmbmKa920Y/voqIYokiY6E6n0kMQbUuuKP+yFkFH23vYDGtymRojQXyhe40X10t/5i+J+d/piOlGVqRzKtsPxr/iAqp/VZcq8XfpZ70fCSNudtJUyzcZ/8AdD9CB0fKRg1c4OZwx9teXI2lNCmLNjkBSIrkYJilE2lRp3ie1uJrC4QxZAoQ0HoPuuwrT+nwXykZ9eqbHd6Xt84NAy3gei3Ghw7zrevUF5eXlrwbviIBEXlReWRDv5jOkvCwWdBKfG2LVgzMyz7xG3Fs/tAprRHNjLg3gFhMvX/duy0JPExK18TM4fr0/pNahGC/7nqJ2PBcssLzigc+j7IxbWWCmILhQIC1xzjJ/a+cQhyzTRaNjgDGxmcxxndzYuGhpqYq3Hl9fT5QnJftc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
